server:
  port: @serverPort@
spring:
  application:
    name: config-server
  profiles:
    active: @activatedProperties@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/poscoict-glueframework/template-config.git
